name: Example-project Deployment
run-name: Example-project is being deployed
env:
  VERCEL_ORG_ID: ${{ secrets.EXAMPLE_PROJECT_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.EXAMPLE_PROJECT_VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/example-project/**
jobs:
  DeployApp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Install Vercel CLI'
        run: npm i -g vercel@latest

      - name: 'Copy vercel config'
        run: |
          mkdir .vercel
          cp -r ./apps/example-project/vercel.json .vercel/project.json

      - name: 'Copy env variables'
        run: |
          vercel env pull .env.development.local --token=${{ secrets.EXAMPLE_PROJECT_VERCEL_TOKEN }}
          mv .env.development.local ./apps/example-project/.env

      - name: 'Build the app'
        run: vercel build --prod

      - name: 'Deploy to Vercel'
        run: vercel --prebuilt --prod --token=${{ secrets.EXAMPLE_PROJECT_VERCEL_TOKEN }}
